version: "3.5"
services:
  rabittmq:
    image: rabbitmq:3.8
    restart: always
    ports:
      - "5672:5672"
    
  db:
    image: mysql:8.0.21
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_USER: root
      MYSQL_PASSWORD: 123123
      MYSQL_DATABASE: icommerce

  product:
    depends_on:
      - rabittmq
      - db
    build: ./product
    environment:
      NODE_ENV: development
      RMQ_ENDPOINT: rabittmq
      RMQ_PORT: 5672
    links:
      - "db"
      - "rabittmq"

  api:
    depends_on:
      - rabittmq
      - product
    build: ./api
    environment:
      NODE_ENV: development
      RMQ_ENDPOINT: rabittmq
      RMQ_PORT: 5672
    links:
      - "db"
      - "rabittmq"
    ports:
      - "3000:3000"
    