version: "3.5"
services:
  rabittmq:
    image: rabbitmq:3.8
    restart: always
    ports:
      - "5672:5672"
    
  db:
    image: mysql:5.7.32
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: icommerce

  product:
    depends_on:
      - rabittmq
      - db
    build: ./ic-product
    environment:
      NODE_ENV: development
      RMQ_ENDPOINT: rabittmq
      RMQ_PORT: 5672
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: 123123
      DB_DATABASE: "icommerce"
    links:
      - "db"
      - "rabittmq"

  api:
    depends_on:
      - rabittmq
      - product
    build: ./ic-api
    environment:
      NODE_ENV: development
      RMQ_ENDPOINT: rabittmq
      RMQ_PORT: 5672
    links:
      - "db"
      - "rabittmq"
    ports:
      - "3000:3000"
    